baseURL: https://holyhope.github.io
languageCode: en-us
title: "@holyhope"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

disqusShortname: holyhope

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: "monokai"
    tabWidth: 4
  
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2

theme:
- chartjs
- holyhope
- mxgraph
- papermod

outputs:
  home:
  - HTML
  - RSS
  - JSON

params:
  env: production
  description: Personal website
  author:
  - "Pierre PÃ‰RONNET <pierre.peronnet@gmail.com>"

  chartjs:
    colors: # https://coolors.co/f94144-f3722c-f8961e-f9c74f-90be6d-43aa8b-577590
    - '#F94144'
    - '#F8961E'
    - '#90BE6D'
    - '#577590'
    - '#F3722C'
    - '#F9C74F'
    - '#43AA8B'

  mxgraph:
    # https://jgraph.github.io/mxgraph/docs/js-api/files/util/mxConstants-js.html
    edgeStyle:
      STYLE_FILLCOLOR: 'var(--code-bg)'
      STYLE_FONTCOLOR: 'var(--content)'
      STYLE_STROKECOLOR: 'var(--secondary)'
      STYLE_FONTFAMILY: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif"
    vertexStyle:
      STYLE_FILLCOLOR: 'var(--code-bg)'
      STYLE_FONTCOLOR: 'var(--content)'
      STYLE_STROKECOLOR: 'var(--border)'
      STYLE_FONTFAMILY: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif"
    cellStyles:
      edgeLabel:
        STYLE_FILLCOLOR: 'var(--code-bg)'
        STYLE_FONTCOLOR: 'var(--primary)'
        STYLE_STROKECOLOR: 'var(--border)'
        STYLE_FONTFAMILY: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif"
      ellipse:
        STYLE_FILLCOLOR: 'var(--code-bg)'
        STYLE_FONTCOLOR: 'var(--primary)'
        STYLE_STROKECOLOR: 'var(--border)'
        STYLE_FONTFAMILY: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif"
      rounded:
        STYLE_FILLCOLOR: 'var(--code-bg)'
        STYLE_FONTCOLOR: 'var(--primary)'
        STYLE_STROKECOLOR: 'var(--border)'
        STYLE_FONTFAMILY: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif"
      default:
        STYLE_FILLCOLOR: 'var(--code-bg)'
        STYLE_FONTCOLOR: 'var(--primary)'
        STYLE_STROKECOLOR: 'var(--border)'
        STYLE_FONTFAMILY: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif"

  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true

  homeInfoParams:
    Title: ""
    Content: "Pierre PÃ‰RONNET *<pierre.peronnet@gmail.com>*"

  profileMode:
    enabled: true
    title: "Welcome ðŸ‘‹"
    subtitle: "To a French g33k website"
    imageUrl: "150x150/me.jpg"
    imageHeight: 150
    imageWidth: 150
    buttons:
    - name: Projects
      url: "/project"
    - name: About me
      url: "/me"

  socialIcons:
  - name: github
    url: https://github.com/holyhope
  - name: email
    url: mailto:pierre.peronnet@gmail.com
  #- name: telegram
  #  url: https://t.me/pierresanseux
  #- name: stackoverflow
  #  url: https://stackoverflow.com/users/13235452/
  - name: linkedin
    url: https://www.linkedin.com/in/holyhope
  - name: slack
    url: https://cloud-native.slack.com/team/UM6BNH0B0

imaging:
  resampleFilter: box
  quality: 75
  bgColor: "#ffffff"
